1:1.c
	gcc 1.c -o 1 -lpthread
2:2.c
	gcc 2.c -o 2 -lpthread
3:3.c
	gcc 3.c -o 3 -lpthread
4:4.c
	gcc 4.c -o 4 -lpthread
5:5.c
	gcc 5.c -o 5 -lpthread
test1:test1.c
	gcc test1.c -o test1
test2:test2.c
	gcc test2.c -o test2
clean:
	rm -f *.o
