15-1:15-1.c
	gcc 15-1.c -o 15-1 -lpthread
15-2:15-2.c
	gcc 15-2.c -o 15-2 -lpthread
15-3:15-3.c
	gcc 15-3.c -o 15-3 -lpthread
final_test:final_test.c
	gcc final_test.c -o final_test -lpthread
p13-7:p13-7.c
	gcc p13-7.c -o p13-7 -lpthread
